[program:ToutDispo-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/ToutDispo/current/artisan queue:work --queue=meta,integrations,critical,default,media,exports --sleep=1 --tries=5 --timeout=60 --max-time=3600
directory=/var/www/ToutDispo/current
user=deploy
numprocs=1
autostart=true
autorestart=true
startsecs=5
startretries=3
stopwaitsecs=3600
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/ToutDispo-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
environment=HOME="/home/deploy",USER="deploy"
