<?php

declare(strict_types=1);

/*
 * Never let a locally cached production/development configuration override
 * phpunit.xml. The isolated path is intentionally never generated by Laravel.
 */
$testConfigCache = __DIR__.'/../bootstrap/cache/testing-config.php';

putenv('APP_CONFIG_CACHE='.$testConfigCache);
$_ENV['APP_CONFIG_CACHE'] = $testConfigCache;
$_SERVER['APP_CONFIG_CACHE'] = $testConfigCache;

require __DIR__.'/../vendor/autoload.php';
